// vue-forms/src/components/RadioInput.vue
<template>
  <p>
    <label>
      <input
        type="radio" name="jsFlavour" value="vanilla" v-model="jsFlavour"
      />
      Vanilla
    </label>
  </p>
  <p>
    <label>
      <input type="radio" name="jsFlavour" value="react" v-model="jsFlavour" />
      React
    </label>
  </p>
  <p>
    <label>
      <input type="radio" name="jsFlavour" value="vue" v-model="jsFlavour" />
      Vue
    </label>
  </p>
  <p>{{ jsFlavour }}</p>
</template>

<script>
import { ref } from 'vue'

export default {
  name: 'RadioInput',
  setup () {
    const jsFlavour = ref('vanilla')
    return {
      jsFlavour
    }
  }
}
</script>

<style scoped>

</style>

// react-forms/src/RadioInput.js
import { useState } from 'react'

export function RadioInput () {
  const [jsFlavour, setJsFlavour] = useState('vanilla')

  const handleChange = (event) => {
    console.log('change', event.target)
    setJsFlavour(event.target.value)
  }

  return (
    <>
      <p>
        <label>
          <input
            type="radio"
            name="jsFlavour"
            value="vanilla"
            onChange={handleChange}
          />
          Vanilla
        </label>
      </p>
      <p>
        <label>
          <input
            type="radio"
            name="jsFlavour"
            value="react"
            onChange={handleChange}
          />
          React
        </label>
      </p>
      <p>
        <label>
          <input
            type="radio"
            name="jsFlavour"
            value="vue"
            onChange={handleChange}
          />
          Vue
        </label>
      </p>
      <p>{jsFlavour}</p>
    </>
  )
}
