// react-forms/src/IncomeCalculator.js
import { useState } from 'react'

export function IncomeCalculator () {
  const [monthlyIncome, setMonthlyIncome] = useState(0)
  const [spouseIncome, setSpouseIncome] = useState(0)

  const annualIncome = (monthlyIncome + spouseIncome) * 12

  return (
    <>
      <h1>Income calculator</h1>

      <p>
        Monthly salary:<br />
        <input
          type="number" value={monthlyIncome}
          onChange={(event) => setMonthlyIncome(Number(event.target.value))}
        />
      </p>
      <p>
        Spouse salary:<br />
        <input
          type="number" value={spouseIncome}
          onChange={(event) => setSpouseIncome(Number(event.target.value))}
        />
      </p>
      <p>
        Annual income:<br />
        {annualIncome}
      </p>
    </>
  )
}

// vue-forms/src/components/IncomeCalculator.vue
<template>
  <h1>Income calculator</h1>
  <p>
    Monthly salary:<br />
    <input type="number" v-model.number="monthlySalary" />
  </p>
  <p>
    Spouse salary:<br />
    <input type="number" v-model.number="spouseSalary" />
  </p>
  <p>
    Annual salary:<br />
    {{ annualIncome }}
  </p>
</template>

<script>
import { computed, ref } from 'vue'

export default {
  name: 'SalaryCalculator',
  setup () {
    const monthlySalary = ref(0)
    const spouseSalary = ref(0)
    const annualIncome = computed(() => (monthlySalary.value + spouseSalary.value) * 12)

    return {
      monthlySalary,
      spouseSalary,
      annualIncome
    }
  }
}
</script>

<style scoped>

</style>
